apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventlog-pvc
  namespace: eventlog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: pv-eventlog
